---
abstract: unknown
author:
  - 'Geoff Richards <qef@laxan.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Warnings: '0'
configure_requires:
  Devel::CheckLib: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Font-FreeType
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.04_01
